<?php

return [

    'standard_response_values' => [
        'SUCCESS' => 1,
        'FAILURE' => 0,
    ],

    'messages'                 => [
        'TRY_AGAIN'                        => 'Please try again!',
        'INVALID_PARAMS'                   => 'Invalid Parameters!',
        'LEADS_CREATE_SUCCESS'             => 'Leads successfuly created.',
        'PROJECT_CREATE_SUCCESS'           => 'Project successfuly created.',
        'VALIDATION_ERROR'                 => 'Validation error occured,Please fill all the required fields.',
        'MATERIALS_CREATE_SUCCESS'         => 'Material successfuly created.',
        'MATERIALS_DELETE_SUCCESS'         => 'Material successfuly deleted.',
        'LABOUR_CREATE_SUCCESS'            => 'Labour successfuly created.',
        'LABOUR_DELETE_SUCCESS'            => 'Labour successfuly deleted.',
        'EQUIPMENT_CREATE_SUCCESS'         => 'Equipment successfuly created.',
        'EQUIPMENT_DELETE_SUCCESS'         => 'Equipment successfuly deleted.',
        'NO_LEADS'                         => 'Oops, No list found!',
        'CLIENT_INFO_UPDATE_SUCCESS'       => 'Client info successfully updated.',
        'LEADS_INFO_UPDATE_SUCCESS'        => 'Leads info successfully updated.',
        'REMINDER_SET_SUCCESS'             => 'Reminder set successfully',
        'DELETE_LEAD_NOTE_SUCCESS'         => 'Lead note successfully deleted.',
        'LEADS_STATUS_CHANGE_SUCCESS'      => 'Leads status successfully changed.',
        'MARK_LEAD_LOST_SUCCESS'           => 'You marked this lead as lost.',
        'TRANSFER_LEAD_SUCCESS'            => 'Yo have successfully transfer lead.',
        'SLIP_STATUS_CHANGED'              => 'Slip status changed successfully',
        'SLIP_STATUS_NOT_CHANGED'          => 'Some Error Occured,slip status has not been changed.',
        'AGREEMENT_END_SUCESS'             => 'Agremeent Ended successfully',
        'CSV_VALIDATION_ERROR'             => 'Please Upload CSV File Only(*.csv)',
        'CSV_PARSED'                       => 'Csv file parsed successfully',
        'UNIT_ADD_SUCCESS'                 => 'Unit has been added successfully',
        'UNIT_NOT_SUCCESS'                 => 'Some Error Occured,Unit has not been added.',
        'UNIT_ASSIGNED_SUCCESS'            => 'Unit assigned successfully',
        'UNIT_ASSIGNED_NOT_SUCCESS'        => 'Some Error Occured,Unit has not been assigned.',
        'FLOOR_ADD_SUCCESS'                => 'Floor has been added successfully',
        'FLOOR_NOT_SUCCESS'                => 'Some Error Occured,Floor has not been added.',
        'BLOCK_ADD_SUCCESS'                => 'Block has been added successfully',
        'BLOCK_NOT_SUCCESS'                => 'Some Error Occured,Block has not been added.',
        //'PROJECT_EDIT_SUCCESS'             => 'Project has been edited successfully',
        'PROJECT_EDIT_SUCCESS'             => 'Project edited successfully.',
        'PROJECT_EDIT_NOT_SUCCESS'         => 'Some Error Occured,Project has not been edited.',
        'UNIT_CONVERTED_GANZA'             => 'Unit has been Successfully converted to Ganza unit.',
        'POW_CREATE_SUCCESS'               => 'POW is created successfully.',
        'TICKET_ADDED_SUCCESS'             => 'Ticket successfully added.',
        'SLIP_ADD_SUCCESS'                 => 'Slip added successfully',
        'SLIP_NOT_SUCCESS'                 => 'Some Error Occured,slip has not been added.',
        'ORDERS_CREATED_SUCCESS'           => 'Order has been created. Admin will approve the order.',
        'SERVICE_FEE_UPDTE_SUCCESS'        => 'Service fee updated successfully.',
        'SERVICE_FEE_UPDTE_FAILURE'        => 'Some Error Occured,service fee has not been updated.',
        'SERVICE_FEE_ADDED_SUCCESS'        => 'Service fee added successfully.',
        'SERVICE_FEE_ADDED_FAILURE'        => 'Some Error Occured,service fee has not been added.',
        'INSTALMENT_ADDED_SUCCESS'         => 'Instalment details added successfully.',
        'INSTALMENT_ADDED_FAILURE'         => 'Some Error Occured,instalment details has not been added.',
        'NO_CONTRACT_FOUND'                => 'No Active agreement found from your details',
        'CONTRACT_FOUND'                   => 'Contract Details found',
        'ORDERS_UPDATE_SUCCESS'            => 'Order has been updated successfully',
        'ATTENDANCE_SUCCESS'               => 'Attendance successfully taken.',
        'ORDER_STATUS_APPROVED'            => 'Order has been successfully approved/placed.',
        'ORDER_CONFIRM_STATUS'             => 'Material received successfully',
        'ORDER_CONFIRM_STATUS'             => 'Material received successfully',
        'DAILY_LABOUR_INFO_UPDATE_SUCCESS' => 'Team info successfully updated.',
        'CHANGE_LABOUR_STATUS_TO_FREE'     => 'This labour is successfully free from this project.',
        'USER_CREATE_SUCCESS'              => 'Staff member created successfully',
        'USER_UPDATED_SUCCESS'             => 'Staff member updated successfully',
        'CANDIDATE_CREATE_SUCCESS'         => 'Candidate created successfully',
        'CANDIDATE_UPDATED_SUCCESS'        => 'Candidate created successfully',
        'DEPARTMENT_CREATE_SUCCESS'        => 'Department created successfully',
        'DEPARTMENT_UPDATED_SUCCESS'       => 'Department created successfully',
        'POSITION_CREATE_SUCCESS'          => 'Position created successfully',
        'PAYROLL_CREATE_SUCCESS'           => 'Payroll generated successfully',
        'ORDER_STATUS_REJECTED'            => 'Order has been deleted.',

    ],

    'paths'                    => [

        'BASEURL_MANAGE'                  => '/manage/',
        'DIR_UPLOADS'                     => '/uploads/',
        'LOGO_FOLDER_PATH'                => '/uploads/logo/',
        'BROCHURE_FOLDER_PATH'            => '/uploads/brochure/',
        'FLOOR_PLAN_FOLDER_PATH'          => '/uploads/floor-plan/',
        'RECEIPT_FOLDER_PATH'             => '/uploads/receipts/',
        'LOGO_PATH'                       => '/public/uploads/logo/',
        'BROCHURE_PATH'                   => '/uploads/brochure/',
        'RECEIPT_PATH'                    => '/public/uploads/receipts/',
        'ASSETS_IMAGE'                    => '/resources/assets/images/',
        'ADMIN_PROFILE_PATH'              => '/profile_pics/',
        'LEADS_ATTACHMENT_PATH'           => '/uploads/leadsattachment/',
        'OFFERLETTER_ATTACMENT_PATH'      => '/uploads/offerletter/',
        'SALES_AGGREMENT_PATH'            => '/uploads/sales-agreement/',
        'AGREEMENT_FOLDER_PATH'           => '/uploads/agreements/',
        'MASTER_PLAN_FOLDER_PATH'         => '/uploads/master-plan/',
        'USER_CV_PATH'                    => '/uploads/staff/cvs/',
        'USER_CV_URL'                     => '/public/uploads/staff/cvs/',
        'CANDIDATE_CV_PATH'               => '/uploads/candidate-cvs/',
        'CANDIDATE_CV_URL'                => '/public/uploads/candidate-cvs/',
        'USER_PHOTO_PATH'                 => '/uploads/staff/photos/',
        'USER_PHOTO_URL'                  => '/public/uploads/staff/photos/',
        'USER_EDUCATION_CERTIFICATE_PATH' => '/uploads/staff/education-certificates/',
        'USER_EDUCATION_CERTIFICATE_URL'  => '/public/uploads/staff/education-certificates/',
        'USER_SAVED_PDF_URL'              => '/public/uploads/staff-details-pdfs/',
        'USER_SAVED_PDF_PATH'             => '/uploads/staff-details-pdfs/',
        'PAYROLL_SAVED_PDF_URL'           => '/public/uploads/staff-generated-payroll/',
        'PAYROLL_SAVED_PDF_PATH'          => '/uploads/staff-generated-payroll/',
        'USER_PERSONAL_ID_PATH'           => '/uploads/staff/personal-ids/',
        'USER_PERSONAL_ID_URL'            => '/public/uploads/staff/personal-ids/',
        'BASEURL_MANAGE'                  => '/manage/',
        'DIR_UPLOADS'                     => '/uploads/',
        'LOGO_FOLDER_PATH'                => '/uploads/logo/',
        'BROCHURE_FOLDER_PATH'            => '/uploads/brochure/',
        'FLOOR_PLAN_FOLDER_PATH'          => '/uploads/floor-plan/',
        'RECEIPT_FOLDER_PATH'             => '/uploads/receipts/',
        'LOGO_PATH'                       => '/public/uploads/logo/',
        'BROCHURE_PATH'                   => '/uploads/brochure/',
        'RECEIPT_PATH'                    => '/public/uploads/receipts/',
        'RECEIPT_PATH_WITHOUT_PUBLIC'     => '/uploads/receipts/',
        'ASSETS_IMAGE'                    => '/resources/assets/images/',
        'ADMIN_PROFILE_PATH'              => '/profile_pics/',
        'LEADS_ATTACHMENT_PATH'           => '/uploads/leadsattachment/',
        'OFFERLETTER_ATTACMENT_PATH'      => '/uploads/offerletter/',
        'SALES_AGGREMENT_PATH'            => '/uploads/sales-agreement/',
        'AGREEMENT_FOLDER_PATH'           => '/uploads/agreements/',
        'MASTER_PLAN_FOLDER_PATH'         => '/uploads/master-plan/',

        'EQUIPMENT_UPLOADS'               => '/uploads/construction-equipment/',
        'EQUIPMENT_UPLOADS_URL'           => '/public/uploads/construction-equipment/',
        'LABOUR_IMAGE_UPLOAD'             => '/uploads/labour-image/',
        'LABOUR_IMAGE_UPLOAD_URL'         => '/public/uploads/labour-image/',
        'RENTAL_AGGREMENT_PATH'           => '/uploads/rental-aggrement/',
        'ASSETS_FRONTHOME_IMAGE'          => '/resources/assets/images/front/',
        'ASSETS_FRONTHOME_IMAGE'          => '/resources/assets/images/front/',

    ],

    'admin_messages'           => [
        'INVALID_PARAMS'          => 'Invalid parameters.',
        'GENERAL_ERROR'           => 'Oops! Something just went wrong. Please try again later.',
        'GENERAL_SUCCESS'         => 'Done!',
        'GENERAL_NO_CHANGES'      => 'You have made no changes.',
        'GENERAL_NO_DATA'         => 'No data available.',
        //'LOGIN_ERROR'             => 'Invalid email address or password.',
        'LOGIN_ERROR'             => 'Invalid login or password.',
        //'LOGIN_SUCCESS'           => 'Authentication completed successfully.',
        'LOGIN_SUCCESS'           => 'Succesfull Authentification.',
        'FORGOT_PASSWORD_SUCCESS' => 'An email has been sent to you. Please check your inbox.',
        'SUCCESS_PASSWORD_CHANGE' => 'Password updated successfully. Redirecting...',
        'NO_DATA_FOUND'           => 'No Data found!',
    ],

    'config_variables'         => [
        'FROM_EMAIL'                       => 'noreply@homex.com',
        'FROM_EMAIL_NAME'                  => 'Homex',
        'EXCEPTION_MAIL_SUBJECT'           => 'Homex: Exception Caught:Beta Server',
        'VIEW_FILE_EXCEPTION'              => 'emails.exception',
        'VIEW_FILE_SERVICE_FEE_PAID'       => 'emails.servicefeepaid',
        'VIEW_FILE_RECEIPT_ACCEPTED'       => 'emails.receiptaccepted',
        'VIEW_FILE_RECEIPT_REJECTED'       => 'emails.receiptrejected',
        'PER_PAGE_RECORDS'                 => '9',
        'INITIAL_PROJECT_STATUS'           => '1',
        'INITIAL_UNIT_STATUS'              => '1',
        'UNIT_STATUS_HOMEX_HOUSING_RENTAL' => '3',
        'MATERIAL_FLAG'                    => 3,
        'EQUIPMENT_FLAG'                   => 1,
        'CHECKLIST_FLAG'                   => 4,
        'LABOUR_FLAG'                      => 2,
        'SERVICE_FEE_CONFIG_ID'            => 1,
        'ORDER_STATUS_REJECTED'            => 6,
        'ORDER_STATUS_APPROVED'            => 5,
        'ORDER_SUBMITTED_STATUS'           => 1,

    ],
    'send_mail_to'             => [
        "ketan@creolestudios.com",
        "jignesh@creolestudios.com",
        "bhargav@creolestudios.com",
        "nivedita@creolestudios.com",
    ],

    'quantity_nos'             => [

    ],
];
